### ISSUE TITLE
KeyError: 'coretemp'

### ISSUE THREAD

**Issue by shubhamlav** [Rizen54/richfetch#1]
Yo. Just installed this in a venv. Yes, I am the venv guy from Discord lol. Got this error:
```py
Traceback (most recent call last):
  File "/home/lav/dev/richfetch/fichretch/./richfetch.py", line 202, in <module>
    system_info = get_system_info()
                  ^^^^^^^^^^^^^^^^^
  File "/home/lav/dev/richfetch/fichretch/./richfetch.py", line 158, in get_system_info
    temp = psutil.sensors_temperatures()['coretemp'][0].current
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'coretemp'
```

**Comment by s-atrn** [comment]
well i've never had this problem maybe an update in the psutil library whouldve caused an issue? I'll check and respond as fast as i can tho i have an exam tomorrow so lets wait a little. **I found a solution**; maybe try installing lm-sensors module which is required to gain access to the hardware sensors.

**Comment by s-atrn** [comment]
I saw this on psutil docs so we know that it's not a hardware or OS issue.
> If sensors are not supported by the OS an empty dict is returned

Try the given solution, and let me know.

**Comment by shubhamlav** [comment]
I thought lm-sensors was installed by default. Well, `sensors` was working fine. Anyways, I did install it via
`sudo pacman -S lm_sensors` and same issue still.

**Comment by shubhamlav** [comment]
This might be of some help.
```py
>>> import psutil
KeyboardInterrupt
>>> import psutil
>>> cpu_temp = psutil.sensors_temperatures()
>>> cpu_temp.keys()
dict_keys(['nvme', 'amdgpu', 'k10temp', 'ath10k_hwmon'])
>>> cpu_temp
{'nvme': [shwtemp(label='Composite', current=35.85, high=79.85, critical=84.85)], 'amdgpu': [shwtemp(label='edge', current=46.0, high=None, critical=None)], 'k10temp': [shwtemp(label='Tctl', current=46.625, high=None, critical=None)], 'ath10k_hwmon': [shwtemp(label='', current=48.0, high=None, critical=None)]}
```

**Comment by shubhamlav** [comment]
I installed psutils from pacman too but that didn't help either.

**Comment by s-atrn** [comment]
Alright got it thanks for sharing that small snippet. The code that fetches temp goes like `temp = psutil.sensors_temperatures()['coretemp'][0].current` and as you provided, the key "coretemp" is not available when you run the thing. So for an instant 
workaround id' suggest you could use the same line of code but replace it with 'nvme' or any of the other keys available.
However the problem here is how do we identify the key to be used since nvme represents the SSD probably? amdgpu represents the gpu and idk anything about the other 2 keys.
Another problem is how do we provide a general solution for other users as well.

**Comment by s-atrn** [comment]
A bit of research showed that `k10temp` shows CPU temp so you can use that for yourself. I'll try putting sort of handling for this, suggestions are highly appreciated. The exact code you can use is `temp = psutil.sensors_temperatures()['k10temp'][0].current`

**Comment by shubhamlav** [comment]
The solution is obvious however I want you to add that feature yourself. I would have submitted a PR but I have to finish another project at the moment.
I do have suggestions for you though but first, I want you to ask this:
**What exactly do you want to show with temperature?**
Is it just the CPU? Or does it also include GPU and other components? I also don't know what temperature coretemp gives us. I presume it is the avg temp of every core of the CPU.

Anyways, you can choose between any of these three implementations:
- Avg temp of every component/sensor.
- Temp of every component listed separately in a single line.
- Just the CPU (or perhaps the GPU too).

1. The implementation of the first should be fairly straight forward.
2. For the second one, what I mean by it is that you list the temp of the RAM, CPU, nvme, GPU, everything and in case there was multiple of something like two nvme cards, you can take their avg and list it there.
3. Lastly, you can also just try to fetch the coretemp and if there is none, like in my case, then you can fetch the k10temp or whatever it was.

In any of these cases tho', do make sure to add an error handler that will mention that sensors are missing or skip over printing sensors and do not just throw an error. The aesthetic of the fetch command is cool and I would have liked to see that instead of an error :p

**Comment by shubhamlav** [comment]
You can close this issue after you submit the PR. You can message me on Discord or ping me here if you need me to do a code review or bug testing or something.
