### ISSUE TITLE
richfetch.py error

### ISSUE THREAD

**Issue by cr1ogen** [Rizen54/richfetch#3]
Give me this error 

```Traceback (most recent call last):
  File "/usr/local/bin/richfetch", line 258, in <module>
    system_info = get_system_info()
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/richfetch", line 209, in get_system_info
    battery = f"{round(psutil.sensors_battery().percent)}%"
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'percent'
```

**Comment by s-atrn** [comment]
Which os are you on?

**Comment by cr1ogen** [comment]
> Which os are you on?

In Debian. Also, since it is a desktop PC, I commented on the lines referring to the battery and it works.

![241010_21-31-35](https://github.com/user-attachments/assets/f030f2c4-1cbb-4685-8ac0-240b6771146a)

**Comment by s-atrn** [comment]
oh its a desktop well yea then it doesnt have a battery, alright i'll fix this.

**Comment by s-atrn** [comment]
also, nice colors, i love the rice.

**Comment by s-atrn** [comment]
please test it and update us if it works

**Comment by cr1ogen** [comment]
> also, nice colors, i love the rice.

Oh Thank you!!!

**Comment by cr1ogen** [comment]
Now give me this 
```
Traceback (most recent call last):
  File "/usr/local/bin/richfetch", line 297, in <module>
    main()
  File "/usr/local/bin/richfetch", line 288, in main
    system_info = get_system_info()
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/richfetch", line 223, in get_system_info
    if plugged == True:
       ^^^^^^^
UnboundLocalError: cannot access local variable 'plugged' where it is not associated with a value
```

**Comment by s-atrn** [comment]
fixed it, git pull and try again

**Comment by cr1ogen** [comment]
Now

```
Traceback (most recent call last):
  File "/usr/local/bin/richfetch", line 300, in <module>
    main()
  File "/usr/local/bin/richfetch", line 291, in main
    system_info = get_system_info()
                  ^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/richfetch", line 222, in get_system_info
    plugged = psutil.sensors_battery().power_plugged
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'power_plugged'
```

**Comment by s-atrn** [comment]
i'm really sorry for continuous errors, since i dont have a pc i cannot test it. you'll have to bear with me a bit. working on it rn

**Comment by s-atrn** [comment]
yup updated, try it again

**Comment by cr1ogen** [comment]
> i'm really sorry for continuous errors, since i dont have a pc i cannot test it. you'll have to bear with me a bit. working on it rn

No please, it's a pleasure to help you.

**Comment by cr1ogen** [comment]
> yup updated, try it again

It works now, thanks!!!

**Comment by s-atrn** [comment]
glad to hear that! feel free to open an Issue or PR if you want to share another error or a new feature or anything!

**Comment by cr1ogen** [comment]
> glad to hear that! feel free to open an Issue or PR if you want to share another error or a new feature or anything!

Thanks, I'll keep that in mind
